{{- if .Values.postgresql.postgresPassword }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-db-init
  labels:
    system: openstack
    type: configuration
    component: database

data:
  db-init.sql: |
    CREATE DATABASE {{.Values.dbName}};
    CREATE ROLE {{.Values.global.dbUser}} WITH ENCRYPTED PASSWORD '{{.Values.global.dbPassword}}' LOGIN;
    GRANT ALL PRIVILEGES ON DATABASE {{.Values.dbName}} TO {{.Values.global.dbUser}};

    CREATE DATABASE {{.Values.apidbName}};
    CREATE ROLE {{.Values.apidbUser}} WITH ENCRYPTED PASSWORD '{{.Values.apidbPassword}}' LOGIN;
    GRANT ALL PRIVILEGES ON DATABASE {{.Values.apidbName}} TO {{.Values.apidbUser}};

    CREATE DATABASE {{.Values.cell0dbName}};
    CREATE ROLE {{.Values.cell0dbUser}} WITH ENCRYPTED PASSWORD '{{.Values.cell0dbPassword | default .Values.apidbPassword}}' LOGIN;
    GRANT ALL PRIVILEGES ON DATABASE {{.Values.cell0dbName}} TO {{.Values.cell0dbUser}};
{{- end }}
