{{- if .Values.postgresql.postgresPassword }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-db-maintain
  labels:
    system: openstack
    type: configuration
    component: database

data:
  db-maintain.sql: |
    CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
    ALTER ROLE {{.Values.global.dbUser}} WITH ENCRYPTED PASSWORD '{{.Values.global.dbPassword}}';
    ALTER ROLE {{.Values.apidbUser}} WITH ENCRYPTED PASSWORD '{{.Values.apidbPassword}}';
    ALTER ROLE {{.Values.postgresql.user}} WITH ENCRYPTED PASSWORD '{{.Values.postgresql.postgresPassword}}';
{{ end }}
