{{- if .Values.vspc.enabled }}
kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: nova-vspc
  namespace: monsoon3
  labels:
    system: openstack
    type: collector
    component: nova
spec:
  replicas: {{ .Values.vspc.replicas | default 1 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      name: nova-vspc
  template:
    metadata:
      labels:
        name: nova-vspc
{{ tuple . "nova" "vspc" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        pod.beta.kubernetes.io/hostname: nova-vspc
        configmap-etc-hash: {{ include (print $.Template.BasePath "/etc-configmap.yaml") . | sha256sum }}
{{- if and (eq .Capabilities.KubeVersion.Major "1") (lt .Capabilities.KubeVersion.Minor "5") }}
        scheduler.alpha.kubernetes.io/affinity: >
            {{ tuple . "nova" "vspc" | include "kubernetes_pod_anti_affinity" }}
{{- end }}
    spec:
{{- if and (eq .Capabilities.KubeVersion.Major "1") (ge .Capabilities.KubeVersion.Minor "7") }}
{{ tuple . "nova" "vspc" | include "kubernetes_pod_anti_affinity" | indent 6 }}
{{- end }}
      hostname: nova-vspc
      containers:
        - name: nova-vspc
          image: {{ tuple . "vspc" | include "container_image_nova" }}
          imagePullPolicy: IfNotPresent
          command: ['dumb-init', 'kubernetes-entrypoint']
          env:
            - name: COMMAND
              value: "nova-vspc --config-file /etc/nova/nova.conf"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPENDENCY_SERVICE
              value: "nova-api"
{{- if .Values.python_warnings }}
            - name: PYTHONWARNINGS
              value: {{ .Values.python_warnings | quote }}
{{- end }}
          volumeMounts:
            - mountPath: /etc/nova
              name: etcnova
            - mountPath: /etc/nova/nova.conf
              name: nova-etc
              subPath: nova.conf
              readOnly: true
            - mountPath: /etc/nova/logging.ini
              name: nova-etc
              subPath: logging.ini
              readOnly: true
            - mountPath: /var/run/serial_log_dir
              name: serial-log-dir
        - name: vmware-vspc
          image: hub.global.cloud.sap/monsoon/vmware-vspc:{{ .Values.vspc.version }}
          imagePullPolicy: IfNotPresent
          command: ['dumb-init', '--', 'vmware-vspc', '--config-file', '/etc/vspc.conf']
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: SENTRY_DSN
              value: {{.Values.sentry_dsn | quote}}
{{- if .Values.python_warnings }}
            - name: PYTHONWARNINGS
              value: {{ .Values.python_warnings | quote }}
{{- end }}
          ports:
            - containerPort: {{ .Values.vspc.portInternal }}
          volumeMounts:
            - mountPath: /var/run/serial_log_dir
              name: serial-log-dir
            - mountPath: /etc/vspc.conf
              name: nova-etc
              subPath: vspc.conf
              readOnly: true
      volumes:
        - name: etcnova
          emptyDir: {}
        - name: nova-etc
          configMap:
            name: nova-etc
        - name: serial-log-dir
          persistentVolumeClaim:
            claimName: {{ .Values.vspc.pvc.existingClaim | default "nova-vspc-pvclaim" }}
{{- end }}
