---
# Source: nova/templates/vspc-service.yaml

kind: Service
apiVersion: v1

metadata:
  name: nova-vspc
  labels:
    system: openstack
    type: backend
    component: nova
spec:
  type: NodePort
  selector:
    name: nova-vspc
  ports:
    - name: vspc
      protocol: TCP
      port: 1333
      targetPort: 1333
  externalIPs:
    - 10.44.11.161
  sessionAffinity: "ClientIP"

